package controlesjava;

import ManejoDatos.Contactos;
import Operaciones.DbContactos;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ContenedorJava.java
 *
 * Created on 21/12/2012, 02:23:56 PM
 */
/**
 *
 * @author hdueñas
 */
public class ContenedorJava extends javax.swing.JFrame {
   ArrayList<Contactos> listaContactos = null; 
   String nombProducto="";
   String codiProducto="";
   byte prdActivo=0;
   DbContactos dbPuente = new DbContactos(); 
    /** Creates new form ContenedorJava */
    public ContenedorJava() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        btnAgregar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblResultados = new javax.swing.JTable();
        jConsultar1 = new javax.swing.JButton();
        btnAgregar1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnAgregar.setText("Agregar Contacto");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        jtblResultados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtblResultados);

        jConsultar1.setText("COnsultar COntacto");
        jConsultar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jConsultar1ActionPerformed(evt);
            }
        });

        btnAgregar1.setText("Eliminar contacto");
        btnAgregar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregar1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Nomb Remitente");

        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField1FocusLost(evt);
            }
        });

        jLabel2.setText("CC Remitente");

        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField2KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addComponent(btnAgregar)
                        .addGap(34, 34, 34)
                        .addComponent(btnAgregar1)))
                .addContainerGap(164, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(311, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(jConsultar1)
                    .addContainerGap(477, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(359, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 153, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar)
                    .addComponent(btnAgregar1))
                .addGap(21, 21, 21))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(326, Short.MAX_VALUE)
                    .addComponent(jConsultar1)
                    .addGap(21, 21, 21)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(30, 30, 30)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(320, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        DbContactos dbContactos = new DbContactos();
        try {
            listaContactos = dbContactos.getListaContactos();
            mostrarTabla(listaContactos);
        } catch (Exception ex) {
            Logger.getLogger(ContenedorJava.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void jConsultar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jConsultar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jConsultar1ActionPerformed

    private void btnAgregar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregar1ActionPerformed
        int i = this.jtblResultados.getSelectedRow();
        if(i>=0){
            long idUser=Long.parseLong(this.jtblResultados.getValueAt(i, (int)0).toString());
            JOptionPane.showMessageDialog(this, "SELECCIONE UN ID: " + idUser);
        }else{
            JOptionPane.showMessageDialog(this, "SELECCIONE UNA FILA: ");
        }// TODO add your handling code here:
    }//GEN-LAST:event_btnAgregar1ActionPerformed

    private void jTextField2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyPressed
        if(esValido(evt.getKeyChar())){
           JOptionPane.showMessageDialog(this, "SOLO SE PERMITEN NUMEROS: " +evt.getKeyChar());
        }
    }//GEN-LAST:event_jTextField2KeyPressed

    private void jTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusLost
      if(!isEmail(jTextField1.getText())){
           JOptionPane.showMessageDialog(this, "NO ES UNA DIR DE EMAIL VALIDA: " );
      }          // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1FocusLost

    /**
     * @param args the command line arguments
     */
     public boolean isEmail(String correo) {
         Pattern pat = null;
         Matcher mat = null;
         pat = Pattern.compile("^([0-9a-zA-Z]([_.w]*[0-9a-zA-Z])*@([0-9a-zA-Z][-w]*[0-9a-zA-Z].)+([a-zA-Z]{2,9}.)+[a-zA-Z]{2,3})$");
         mat = pat.matcher(correo);
         if (mat.find()) {
             System.out.println("[" + mat.group() + "]");
             return true;
         }else{
             return false;
         }
    }
   
    public boolean esValido(Character caracter){
       char c = caracter.charValue();
       if ( !(Character.isLetter(c) //si es letra
           || c == ' ' //o un espacio
           || c == 8 //o backspace
        ))
        return false;
       else
         return true;

   }

    private void mostrarTabla(ArrayList<Contactos> listaContactos) {
        //Se cuenta la cantidad de columnas que contendrá la tabla
        final int cantCols;
        cantCols = 4;
                
        //Nombres de las columnas
        String[] nombCols = new String[cantCols];
        nombCols[0] = "Id Producto";
        nombCols[1] = "Nombre Producto";
        nombCols[2] = "Activo";
        nombCols[3] = "Codigo ISO";
        
        int i = 4;
        //Contenido de la tabla
        
        String [][] cuerpoTabla = new String[listaContactos.size()][0];
        for(int k = 0; k < listaContactos.size(); k++) {
                Contactos puenteAux = (Contactos)listaContactos.get(k);
                String[] registroAux = new String[cantCols];
                registroAux[0] = "" + puenteAux.getIdRemitente();
                registroAux[1] = puenteAux.getCodiPrd();
                registroAux[2] = "" + puenteAux.getTablaPuenteTmp();
                registroAux[3] = puenteAux.getCodiPrd();
                cuerpoTabla[k] = registroAux;
       }
        
        DefaultTableModel tablaResultados = new DefaultTableModel(cuerpoTabla, nombCols) {
            
            boolean[] canEdit = new boolean [cantCols];
            
            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        };
        jtblResultados.setModel(tablaResultados);
        jtblResultados.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        TableColumnModel columnas = jtblResultados.getColumnModel();
        columnas.getColumn(0).setPreferredWidth(70);
        columnas.getColumn(1).setPreferredWidth(300);
        columnas.getColumn(2).setPreferredWidth(100);
        columnas.getColumn(3).setPreferredWidth(130);
                
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnAgregar1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jConsultar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTable jtblResultados;
    // End of variables declaration//GEN-END:variables
}
